# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kMcCEs1d3DxJ6eRqFMNUhlO_5uWDbHwL
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/updated_sentiment_analysis(2).csv")

df.sample(20000)

y=df.iloc[:,-1].values

print(x)

print(y)

print(x.shape)

print(y.shape)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2021, test_size=0.2)

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense

ann_model=Sequential()

ann_model.add( Dense(8, activation="sigmoid", input_shape = (x.shape[1],) ) )
ann_model.add( Dense(8, activation="sigmoid") )
ann_model.add( Dense(1, activation="sigmoid"))

ann_model.compile(optimizer='Adam', loss="binary_crossentropy", metrics=['accuracy'])

ann_model.fit(x, y, batch_size=10, epochs=30, validation_data=(x_test,y_test),verbose=1)

ann_model.evaluate(x_test, y_test, verbose = 0)